### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by anzi121** [abdulbaquee/unofficial-google-my-business#1]
Hi Abdul

Can you please do you have any PHP Script where we can create google MAP approved listing without any verification?

Thanks!

**Comment by anzi121** [comment]
Hi @abdulbaquee 

I am facing error when redirecting to the account 

Fatal error: Uncaught Exception: Client ID is missing in /home/wmiserve/public_html/mybusiness/lib/Google_my_business.php:698 Stack trace: #0 /home/wmiserve/public_html/mybusiness/lib/Google_my_business.php(54): Google_my_business->_show_error('Client ID is mi...') #1 /home/wmiserve/public_html/mybusiness/locations.php(8): Google_my_business->__construct('994305388798-lm...', '1kPD3UgM_JgHFbF...', 'https://wmiserv...', Array) #2 {main} thrown in /home/wmiserve/public_html/mybusiness/lib/Google_my_business.php on line 698

**Comment by abdulbaquee** [comment]
Hello @ansarul121,

Hope you are well and healthy.

Can please refer the doc of Google my business API as mentioned below:
https://developers.google.com/my-business/reference/rest/v4/accounts/create

Please let me know if you are looking anything else.

**Comment by anzi121** [comment]
Okay Thanks @abdulbaquee
 
Can you please help me do you have any module for google by business where we can create listing and approved , i got approvel google my business API 

If you are chage any cost , i will be very happy to provide you the cost 

Thanks !

Waiting for your reply

**Comment by abdulbaquee** [comment]
Hello @ansarul121, 

Let's discuss on email: abdulbaquee@gmail.com 

Thanks & Regards!

**Comment by anzi121** [comment]
Hi @abdulbaquee 

I have send you email 
Thanks !

My email:info@webmatrixindia.com

**Comment by abdulbaquee** [comment]
You are missing "Client ID". So please follow the proper readme file instruction.
